CREATE DATABASE IF NOT EXISTS rosdb;

USE rosdb;

CREATE TABLE IF NOT EXISTS turtlepos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    theta FLOAT NOT NULL,
    time DATETIME NOT NULL
);